import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class InfoService {
  constructor() {}

  countries = [
    { value: "Singaporean" },
    { value: "Afghan" },
    { value: "Albanian" },
    { value: "Algerian" },
    { value: "American" },
    { value: "Andorran" },
    { value: "Angolan" },
    { value: "Antiguans" },
    { value: "Argentinean" },
    { value: "Armenian" },
    { value: "Australian" },
    { value: "Austrian" },
    { value: "Azerbaijani" },
    { value: "Bahamian" },
    { value: "Bahraini" },
    { value: "Bangladeshi" },
    { value: "Barbadian" },
    { value: "Barbudans" },
    { value: "Batswana" },
    { value: "Belarusian" },
    { value: "Belgian" },
    { value: "Belizean" },
    { value: "Beninese" },
    { value: "Bhutanese" },
    { value: "Bolivian" },
    { value: "Bosnian" },
    { value: "Brazilian" },
    { value: "British" },
    { value: "Bruneian" },
    { value: "Bulgarian" },
    { value: "Burkinabe" },
    { value: "Burmese" },
    { value: "Burundian" },
    { value: "Cambodian" },
    { value: "Cameroonian" },
    { value: "Canadian" },
    { value: "Cape Verdean" },
    { value: "Central African" },
    { value: "Chadian" },
    { value: "Chilean" },
    { value: "Chinese" },
    { value: "Colombian" },
    { value: "Comoran" },
    { value: "Congolese" },
    { value: "Costa Rican" },
    { value: "Croatian" },
    { value: "Cuban" },
    { value: "Cypriot" },
    { value: "Czech" },
    { value: "Danish" },
    { value: "Djibouti" },
    { value: "Dominican" },
    { value: "Dutch" },
    { value: "East Timorese" },
    { value: "Ecuadorean" },
    { value: "Egyptian" },
    { value: "Emirian" },
    { value: "Equatorial Guinean" },
    { value: "Eritrean" },
    { value: "Estonian" },
    { value: "Ethiopian" },
    { value: "Fijian" },
    { value: "Filipino" },
    { value: "Finnish" },
    { value: "French" },
    { value: "Gabonese" },
    { value: "Gambian" },
    { value: "Georgian" },
    { value: "German" },
    { value: "Ghanaian" },
    { value: "Greek" },
    { value: "Grenadian" },
    { value: "Guatemalan" },
    { value: "Guinea-Bissauan" },
    { value: "Guinean" },
    { value: "Guyanese" },
    { value: "Haitian" },
    { value: "Herzegovinian" },
    { value: "Honduran" },
    { value: "Hungarian" },
    { value: "I-Kiribati" },
    { value: "Icelander" },
    { value: "Indian" },
    { value: "Indonesian" },
    { value: "Iranian" },
    { value: "Iraqi" },
    { value: "Irish" },
    { value: "Israeli" },
    { value: "Italian" },
    { value: "Ivorian" },
    { value: "Jamaican" },
    { value: "Japanese" },
    { value: "Jordanian" },
    { value: "Kazakhstani" },
    { value: "Kenyan" },
    { value: "Kittian and Nevisian" },
    { value: "Kuwaiti" },
    { value: "Kyrgyz" },
    { value: "Laotian" },
    { value: "Latvian" },
    { value: "Lebanese" },
    { value: "Liberian" },
    { value: "Libyan" },
    { value: "Liechtensteiner" },
    { value: "Lithuanian" },
    { value: "Luxembourger" },
    { value: "Macedonian" },
    { value: "Malagasy" },
    { value: "Malawian" },
    { value: "Malaysian" },
    { value: "Maldivan" },
    { value: "Malian" },
    { value: "Maltese" },
    { value: "Marshallese" },
    { value: "Mauritanian" },
    { value: "Mauritian" },
    { value: "Mexican" },
    { value: "Micronesian" },
    { value: "Moldovan" },
    { value: "Monacan" },
    { value: "Mongolian" },
    { value: "Moroccan" },
    { value: "Mosotho" },
    { value: "Motswana" },
    { value: "Mozambican" },
    { value: "Namibian" },
    { value: "Nauruan" },
    { value: "Nepalese" },
    { value: "New Zealander" },
    { value: "Nicaraguan" },
    { value: "Nigerian" },
    { value: "Nigerien" },
    { value: "North Korean" },
    { value: "Northern Irish" },
    { value: "Norwegian" },
    { value: "Omani" },
    { value: "Pakistani" },
    { value: "Palauan" },
    { value: "Panamanian" },
    { value: "Papua New Guinean" },
    { value: "Paraguayan" },
    { value: "Peruvian" },
    { value: "Polish" },
    { value: "Portuguese" },
    { value: "Qatari" },
    { value: "Romanian" },
    { value: "Russian" },
    { value: "Rwandan" },
    { value: "Saint Lucian" },
    { value: "Salvadoran" },
    { value: "Samoan" },
    { value: "San Marinese" },
    { value: "Sao Tomean" },
    { value: "Saudi" },
    { value: "Scottish" },
    { value: "Senegalese" },
    { value: "Serbian" },
    { value: "Seychellois" },
    { value: "Sierra Leonean" },
    { value: "Singaporean" },
    { value: "Slovakian" },
    { value: "Slovenian" },
    { value: "Solomon Islander" },
    { value: "Somali" },
    { value: "South African" },
    { value: "South Korean" },
    { value: "Spanish" },
    { value: "Sri Lankan" },
    { value: "Sudanese" },
    { value: "Surinamer" },
    { value: "Swazi" },
    { value: "Swedish" },
    { value: "Swiss" },
    { value: "Syrian" },
    { value: "Taiwanese" },
    { value: "Tajik" },
    { value: "Tanzanian" },
    { value: "Thai" },
    { value: "Togolese" },
    { value: "Tongan" },
    { value: "Trinidadian or Tobagonian" },
    { value: "Tunisian" },
    { value: "Turkish" },
    { value: "Tuvaluan" },
    { value: "Ugandan" },
    { value: "Ukrainian" },
    { value: "Uruguayan" },
    { value: "Uzbekistani" },
    { value: "Venezuelan" },
    { value: "Vietnamese" },
    { value: "Welsh" },
    { value: "Yemenite" },
    { value: "Zambian" },
    { value: "Zimbabwean" },
  ];

  status = [
    { value: "employed" },
    { value: "actively looking" },
    { value: "not looking" },
  ];
}
